//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schools_Management_System.School_Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresentAddress
    {
        public int PresentAddressID { get; set; }
        public string PresentVllage { get; set; }
        public string PresentRoad { get; set; }
        public string PresentDistrict { get; set; }
        public string PresentUpazila { get; set; }
        public string PresentPostOffice { get; set; }
        public string PresentPostCode { get; set; }
        public int StudentID { get; set; }
    
        public virtual StudentInformation StudentInformation { get; set; }
    }
}
