//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schools_Management_System.School_Data_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class schoolmanagementsystemEntities : DbContext
    {
        public schoolmanagementsystemEntities()
            : base("name=schoolmanagementsystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<GuirdianInformation> GuirdianInformations { get; set; }
        public virtual DbSet<ImagesForAll> ImagesForAlls { get; set; }
        public virtual DbSet<PermanentAddress> PermanentAddresses { get; set; }
        public virtual DbSet<PresentAddress> PresentAddresses { get; set; }
        public virtual DbSet<SecurityQuestion> SecurityQuestions { get; set; }
        public virtual DbSet<StudentInformation> StudentInformations { get; set; }
        public virtual DbSet<StudentMonthlyFee> StudentMonthlyFees { get; set; }
        public virtual DbSet<StudentMonthlyFeesAmount> StudentMonthlyFeesAmounts { get; set; }
        public virtual DbSet<StudentMonthlyFeesData> StudentMonthlyFeesDatas { get; set; }
        public virtual DbSet<StudentShiftInfo> StudentShiftInfoes { get; set; }
        public virtual DbSet<Upazila> Upazilas { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserQuestion> UserQuestions { get; set; }
    }
}
