//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schools_Management_System.School_Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMonthlyFee
    {
        public int PayID { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime AmountPayDate { get; set; }
        public Nullable<int> StudentID { get; set; }
    
        public virtual StudentInformation StudentInformation { get; set; }
    }
}
