//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schools_Management_System.School_Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentInformation()
        {
            this.GuirdianInformations = new HashSet<GuirdianInformation>();
            this.ImagesForAlls = new HashSet<ImagesForAll>();
            this.PermanentAddresses = new HashSet<PermanentAddress>();
            this.PresentAddresses = new HashSet<PresentAddress>();
            this.StudentMonthlyFees = new HashSet<StudentMonthlyFee>();
            this.StudentMonthlyFeesAmounts = new HashSet<StudentMonthlyFeesAmount>();
            this.StudentMonthlyFeesDatas = new HashSet<StudentMonthlyFeesData>();
        }
    
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentFather_sName { get; set; }
        public string StudentMother_sName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string StudentAge { get; set; }
        public string StudentStandar { get; set; }
        public string SudentRollNo { get; set; }
        public string StudentBirthReg { get; set; }
        public string StudentEmail { get; set; }
        public string SudentSession { get; set; }
        public string StudentGender { get; set; }
        public string StudentMobile { get; set; }
        public string StudentNationality { get; set; }
        public int ShiftID { get; set; }
        public System.DateTime StudentAdmissionDate { get; set; }
        public string StudentDurations { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuirdianInformation> GuirdianInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagesForAll> ImagesForAlls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermanentAddress> PermanentAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresentAddress> PresentAddresses { get; set; }
        public virtual StudentShiftInfo StudentShiftInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentMonthlyFee> StudentMonthlyFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentMonthlyFeesAmount> StudentMonthlyFeesAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentMonthlyFeesData> StudentMonthlyFeesDatas { get; set; }
    }
}
