//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schools_Management_System.School_Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuestion
    {
        public int SecurityQuestionID { get; set; }
        public string QuestionOne { get; set; }
        public string AnswerOne { get; set; }
        public string QuestionTwo { get; set; }
        public string AnswerTwo { get; set; }
        public int UserID { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
